# Generated by Django 3.1 on 2020-08-08 22:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=datetime.date.today)),
                ('end_time', models.DateTimeField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Some string', editable=False, max_length=25)),
                ('last_name', models.CharField(default='Some string', editable=False, max_length=25)),
                ('activityperiod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.activityperiod')),
            ],
        ),
    ]
