# Generated by Django 3.1 on 2020-08-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_user_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityperiod',
            name='ref',
        ),
        migrations.RemoveField(
            model_name='activityperiod',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='country',
        ),
        migrations.AddField(
            model_name='activityperiod',
            name='id',
            field=models.AutoField(auto_created=True, default=-1.0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Some string', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Some string', max_length=25, null=True),
        ),
    ]
